export enum EntityEnums {
  User = 'user',
  Plant = 'plant',
  PlantType = 'plant_type',
  SensorReadings = 'sensor_readings',
  UserActions = 'user_actions',
  SubscriptionTier = 'subscription_tiers',
  UserSubscription = 'user_subscriptions',
  Device = 'device',
  PlantGroupEntity = 'plant_groups',
  PlantSpecies='plant_species',
  PlantPackage='plant_packages',
  PlantPackageItem= 'plant_package_items',
  UserPlantSelection = 'user_plant_selections',
  UserAction = 'user_actions',
  SensorVerification = 'sensor_verifications',
}
